<!DOCTYPE html>
<html>

<head>

<meta charset="utf-8">

<title>Booking Report</title>

<style>

*{
margin:0;
padding:0;
box-sizing:border-box;
}

body{
font-family:DejaVu Sans,sans-serif;
font-size:11px;
color:#222;
padding:25px;
}

.header{
text-align:center;
margin-bottom:25px;
}

.header h1{
font-size:22px;
margin-bottom:6px;
}

.header h2{
font-size:17px;
font-weight:normal;
margin-bottom:5px;
}

.header p{
font-size:11px;
color:#666;
}

.summary{
margin:20px 0;
}

.summary table{
width:100%;
border-collapse:collapse;
}

.summary td{
padding:6px 10px;
border:1px solid #ddd;
}

table{
width:100%;
border-collapse:collapse;
margin-top:15px;
}

thead{
background:#2d3748;
color:#fff;
}

th{
padding:10px;
border:1px solid #000;
font-size:11px;
text-align:left;
}

td{
padding:8px;
border:1px solid #ccc;
vertical-align:top;
font-size:10px;
}

tbody tr:nth-child(even){
background:#f5f5f5;
}

.footer{
position:fixed;
bottom:-20px;
left:0;
right:0;
text-align:center;
font-size:10px;
color:#666;
}

</style>

</head>

<body>

<div class="header">

<h1>

Sports Facility Booking System

</h1>

<h2>

Booking Report

</h2>

<p>

Generated on

{{ now()->format('d F Y, h:i A') }}

</p>

</div>

<div class="summary">

<table>

<tr>

<td>

<strong>Total Records</strong>

</td>

<td>

{{ $bookings->count() }}

</td>

<td>

<strong>Generated By</strong>

</td>

<td>

{{ auth()->user()->name }}

</td>

</tr>

</table>

</div>

<table>

<thead>

<tr>

<th width="4%">

No

</th>

<th width="18%">

Student

</th>

<th width="18%">

Facility

</th>

<th width="11%">

Date

</th>

<th width="12%">

Time

</th>

<th width="12%">

Status

</th>

<th width="25%">

Purpose

</th>

</tr>

</thead>

<tbody>

@forelse($bookings as $booking)

<tr>

<td>

{{ $loop->iteration }}

</td>

<td>

<strong>

{{ $booking->user->name }}

</strong>

<br>

{{ $booking->user->student_id }}

<br>

{{ $booking->user->email }}

</td>

<td>

{{ $booking->facility->facility_name }}

</td>

<td>

{{ \Carbon\Carbon::parse($booking->booking_date)->format('d/m/Y') }}

</td>

<td>

{{ \Carbon\Carbon::parse($booking->start_time)->format('g:i A') }}

-

{{ \Carbon\Carbon::parse($booking->end_time)->format('g:i A') }}

</td>

<td>

{{ ucfirst($booking->booking_status) }}

</td>

<td>

{{ $booking->purpose }}

</td>

</tr>

@empty

<tr>

<td colspan="7" align="center">

No booking records found.

</td>

</tr>

@endforelse

</tbody>

</table>

<div class="footer">

Sports Facility Booking System

|

Page <script type="text/php">

if(isset($pdf)){

$font=$fontMetrics->get_font("Helvetica","normal");

$pdf->page_text(

520,

810,

"Page {PAGE_NUM} of {PAGE_COUNT}",

$font,

10

);

}

</script>

</div>

</body>

</html>